// $(function(){
//     $('.imgtext').hide()
//     $('.conimg1').hover(function(){
//         $('.imgtext').show()
//         $('.span').hide()
//     },function(){
//         $('.imgtext').hide()
//         $('.span').show()
//     })
// })